title: Yinkai Zhu's Homepage
page-top-title: Yinkai Zhu
top-section-bg-text: Embodied Artificial Intelligence
home-subtitle: Yinkai Zhu&ensp;|&ensp;朱胤恺
copyright-text: '&copy; Yinkai Zhu 2024-2025. All Rights Reserved.'
